2021-11-06 16:22:00,918 INFO    MainThread:6809 [wandb_setup.py:_flush():71] setting env: {}
2021-11-06 16:22:00,918 INFO    MainThread:6809 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-06 16:22:00,918 INFO    MainThread:6809 [wandb_init.py:_log_setup():357] Logging user logs to /home/ubuntu/cgiar_repo/cgiar-malaria/wandb/run-20211106_162200-1p18yuw6/logs/debug.log
2021-11-06 16:22:00,918 INFO    MainThread:6809 [wandb_init.py:_log_setup():358] Logging internal logs to /home/ubuntu/cgiar_repo/cgiar-malaria/wandb/run-20211106_162200-1p18yuw6/logs/debug-internal.log
2021-11-06 16:22:00,918 INFO    MainThread:6809 [wandb_init.py:init():390] calling init triggers
2021-11-06 16:22:00,918 INFO    MainThread:6809 [wandb_init.py:init():397] wandb.init called with sweep_config: {}
config: {}
2021-11-06 16:22:00,918 INFO    MainThread:6809 [wandb_init.py:init():435] starting backend
2021-11-06 16:22:00,919 INFO    MainThread:6809 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-06 16:22:00,930 INFO    MainThread:6809 [backend.py:ensure_launched():199] starting backend process...
2021-11-06 16:22:00,935 INFO    MainThread:6809 [backend.py:ensure_launched():205] started backend process with pid: 6857
2021-11-06 16:22:00,937 INFO    MainThread:6809 [wandb_init.py:init():444] backend started and connected
2021-11-06 16:22:00,939 INFO    MainThread:6809 [wandb_init.py:init():503] updated telemetry
2021-11-06 16:22:00,956 INFO    MainThread:6809 [wandb_init.py:init():533] communicating current version
2021-11-06 16:22:01,715 INFO    MainThread:6809 [wandb_init.py:init():538] got version response 
2021-11-06 16:22:01,715 INFO    MainThread:6809 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-11-06 16:22:01,833 INFO    MainThread:6809 [wandb_init.py:init():576] starting run threads in backend
2021-11-06 16:22:01,868 INFO    MainThread:6809 [wandb_run.py:_console_start():1693] atexit reg
2021-11-06 16:22:01,869 INFO    MainThread:6809 [wandb_run.py:_redirect():1567] redirect: SettingsConsole.REDIRECT
2021-11-06 16:22:01,870 INFO    MainThread:6809 [wandb_run.py:_redirect():1572] Redirecting console.
2021-11-06 16:22:01,875 INFO    MainThread:6809 [wandb_run.py:_redirect():1628] Redirects installed.
2021-11-06 16:22:01,875 INFO    MainThread:6809 [wandb_init.py:init():603] run started, returning control to user process
2021-11-06 16:22:01,877 INFO    MainThread:6809 [wandb_run.py:_config_callback():911] config_cb None None {'model_opts': {'name': 'Unet', 'args': {'inchannels': 3, 'outchannels': 1, 'net_depth': 5, 'dataset': 'water', 'epochs': 100, 'batch': 4, 'workers': 1, 'lr': 0.001}}}
2021-11-06 16:22:01,935 INFO    MainThread:6809 [wandb_run.py:_atexit_cleanup():1663] got exitcode: 1
2021-11-06 16:22:01,937 INFO    MainThread:6809 [wandb_run.py:_restore():1635] restore
2021-11-06 16:22:04,384 INFO    MainThread:6809 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 771
  total_bytes: 771
}

2021-11-06 16:22:04,494 INFO    MainThread:6809 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 771
  total_bytes: 771
}

2021-11-06 16:22:04,847 INFO    MainThread:6809 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 771
  total_bytes: 2668
}

2021-11-06 16:22:04,948 INFO    MainThread:6809 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1729
  total_bytes: 2668
}

2021-11-06 16:22:05,050 INFO    MainThread:6809 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2668
  total_bytes: 2668
}

2021-11-06 16:22:05,152 INFO    MainThread:6809 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2668
  total_bytes: 2668
}

2021-11-06 16:22:05,255 INFO    MainThread:6809 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2668
  total_bytes: 2668
}

2021-11-06 16:22:05,357 INFO    MainThread:6809 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2668
  total_bytes: 2668
}

2021-11-06 16:22:05,549 INFO    MainThread:6809 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2668
  total_bytes: 2668
}

2021-11-06 16:22:05,758 INFO    MainThread:6809 [wandb_run.py:_wait_for_finish():1793] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2668
  total_bytes: 2668
}
local_info {
}

2021-11-06 16:22:06,851 INFO    MainThread:6809 [wandb_run.py:_append_files():2061] logging synced files
